GET http://localhost:8080/rest/v1/user/all

###

GET http://localhost:8080/rest/v1/user/4/id

###

GET http://localhost:8080/rest/v1/product/all

###

GET http://localhost:8080/rest/v1/product/7/id

###

POST http://localhost:8080/rest/v1/user
Authorization: Basic 444 rrrRRR111
Content-Type: application/json

{
  "username": "userTestttttttttt",
  "email": "userTestttttttttt@mail.ru",
  "password": "rrrRRR111"
}

###

PUT http://localhost:8080/rest/v1/user
Authorization: Basic 444 rrrRRR111
Content-Type: application/json

{
  "id": "3",
  "username": "222",
  "email": "123@mail.ru",
  "password": "rrrRRR1111"
}

###

POST http://localhost:8080/rest/v1/product
Authorization: Basic 444 rrrRRR111
Content-Type: application/json

{
"title": "testProduct",
"cost": "606"
}

###